Artists = [
    {'name':'Drake'},
    {'name':'Beyonce'},
    {'name':'Taylor Swift'},
    {'name':'Her''s'},
    {'name':'Bad Suns'},
    {'name':'Sarah Kinsely'},
    {'name':'Bob Marley & The Wailers'},
    {'name':'Jack Johnson'},
    {'name':'Guts'},
    {'name':'Ours Samplus'},
    {'name':'Nina Simone'},
    {'name':'Gucci Mane'},
    {'name':'YG'},
    {'name':'Kendrick Lamar'},
    {'name':'Mac Dre'},
    {'name':'MICHELLE'},
    {'name':'Cosmic Boy'},
    {'name':'Richie Quake'},
    {'name':'chloe moriondo'},
    {'name':'DEAN'},
    {'name':'HYUKOH'},
    {'name':'offonoff'},
    {'name':'DPR IAN'},
    {'name':'Rihanna'},
    {'name':'SZA'},
    {'name':'Khalid'},
    {'name':'Jaden'},
    {'name':'Post Malone'},
    {'name':'Juice WRLD'},
    {'name':'Epik High'},
]