# Generated by Django 4.2.6 on 2023-10-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('image', models.URLField(max_length=250)),
            ],
        ),
    ]
